import { useState } from 'react'
import Head from 'next/head'

const MOMENTS={
  bridgerton:{label:'Bridgerton universe',mechanism:'Aesthetic association hypothesis',summary:'Repeated exposure to a coherent fictional world may strengthen associations among its visual cues, emotions, and identity aspirations. Commercial activity can be consistent with that hypothesis, but these public signals do not establish causation.',evidence:['Associative learning','Narrative transportation','Possible identity signaling']},
  mj:{label:'Michael Jackson biopic',mechanism:'Retrospective identity exploration',summary:'A biopic can introduce an earlier aesthetic to audiences without lived nostalgia. Search and coverage changes may show attention, but they cannot tell us whether a new self-concept or purchase behavior followed.',evidence:['Cultural rediscovery','Social learning','Attention is not conversion']},
  yellowstone:{label:'Yellowstone / Dutton Ranch',mechanism:'Place and identity signaling hypothesis',summary:'A media setting can become shorthand for values or a desired lifestyle. Public attention may help teams form questions about place-linked identity, but it does not demonstrate purchase intent.',evidence:['Place attachment','Possible identity signaling','Validate with audience research']},
  euphoria:{label:'Euphoria',mechanism:'Character-linked aesthetic diffusion',summary:'Characters can help make an aesthetic legible and shareable. Observed attention is useful for exploration, not proof that viewers adopted a character identity or changed behavior.',evidence:['Observational learning','Aesthetic diffusion','Correlation only']}
}

export default function Home(){
 const [moment,setMoment]=useState(''); const [data,setData]=useState(null); const [status,setStatus]=useState('idle');
 async function choose(id){setMoment(id);setData(null);if(!id){setStatus('idle');return}setStatus('loading');try{const r=await fetch(`/api/signal?moment=${encodeURIComponent(id)}`);if(!r.ok)throw new Error();setData(await r.json());setStatus('ready')}catch{setStatus('error')}}
 const item=MOMENTS[moment];
 return <><Head><title>Behavioral Intelligence Layer — Aloha AI Consulting</title><meta name="description" content="An issue-spotting layer for exploring screen-culture attention signals and testable consumer-behavior hypotheses."/><link rel="canonical" href="https://aloha-behavioral-intelligence.vercel.app/"/><link rel="icon" href="/favicon.svg"/><meta name="theme-color" content="#1b7a68"/><meta name="robots" content="index, follow"/></Head>
 <a className="skip" href="#main">Skip to main content</a><header><div><strong>Aloha AI Consulting</strong><span>Behavioral Intelligence Layer</span></div><small>Method review · August 19, 2026</small></header>
 <main id="main"><p className="eyebrow">Exploratory issue-spotter</p><h1>Screen culture → testable behavior hypotheses</h1><p className="lede">Choose a culture moment to examine a cautious behavioral hypothesis alongside current public attention samples. This tool does not measure an individual, predict behavior, or establish that media exposure caused a purchase.</p>
 <label htmlFor="moment">Culture moment</label><select id="moment" value={moment} onChange={e=>choose(e.target.value)}><option value="">Choose a signal…</option>{Object.entries(MOMENTS).map(([id,m])=><option key={id} value={id}>{m.label}</option>)}</select>
 <p className="status" role="status" aria-live="polite">{status==='loading'?'Loading public-source samples…':status==='error'?'Signals are temporarily unavailable. The hypothesis remains visible, but no current sample is shown.':''}</p>
 {item&&<section className="stack" aria-labelledby="mechanism"><article><p className="eyebrow">Behavioral hypothesis</p><h2 id="mechanism">{item.mechanism}</h2><p>{item.summary}</p><div className="tags">{item.evidence.map(x=><span key={x}>{x}</span>)}</div></article>
 <div className="metrics"><article><span>Wikipedia pageviews</span><strong>{data?.wiki?.daily?.toLocaleString?.()??'—'}</strong><small>{data?.wiki?`Daily average across ${data.wiki.days} available UTC days`:'Public attention sample'}</small></article><article><span>Reddit search sample</span><strong>{data?.reddit?.postCount??'—'}</strong><small>Up to 10 results from one named subreddit</small></article><article><span>Google News RSS sample</span><strong>{data?.news?.length??'—'}</strong><small>Up to 5 query matches; not a total story count</small></article></div>
 {data&&<p className="stamp">Fetched {new Date(data.fetchedAt).toLocaleString()} · Sources can be incomplete, delayed, or unavailable.</p>}
 {data?.news?.length>0&&<article><h2>Recent query matches</h2><ul>{data.news.map((n,i)=><li key={i}>{n.link?<a href={n.link} target="_blank" rel="noreferrer">{n.title}</a>:n.title}<small>{n.source}{n.date?` · ${n.date}`:''}</small></li>)}</ul></article>}
 </section>}
 <section className="boundary"><h2>Use boundary</h2><p>Use these signals to form research questions. Validate any strategic decision with audience research, sales or conversion data, and cultural review. Do not use this page to infer sensitive traits, target vulnerable people, or score individuals.</p></section></main>
 <footer><span>RN Collins · Aloha AI Consulting</span><nav aria-label="Footer"><a href="/sources">Sources & method</a><a href="/privacy">Privacy</a><a href="https://aloha-ai-consulting.vercel.app">Consulting hub</a></nav></footer></>
}
